parameters:

    szg_feed.elastic_search_items_provider_class: 'SZG\KunstmaanFeedBundle\Services\Provider\ElasticSearchItemsProvider'
    szg_feed.elastic_search_items_provider_attributes_normalizer_class: 'SZG\KunstmaanFeedBundle\Services\Provider\ElasticSearchItemProviderAttributesNormalizer'
    szg_feed.elastic_search_searcher_class: 'SZG\KunstmaanFeedBundle\Services\Searcher\ElasticaSearcher'

services:

    szg_feed.elastic_search_searcher:
       class: '%szg_feed.elastic_search_searcher_class%'
       parent: kunstmaan_node_search.search.abstract_elastica_searcher
       public: false
       arguments:
          - '@kunstmaan_extra.site_tree.current_locale'
          - '@kunstmaan_admin.domain_configuration'
          - '%kunstmaan_node_search.indexname%'
          - '%kunstmaan_node_search.indextype%'

    szg_feed.elastic_search_items_provider:
        class: "%szg_feed.elastic_search_items_provider_class%"
        arguments:
          - '@szg_feed.elastic_search_searcher'
          - '@szg_feed.elastic_search_items_provider_attributes_normalizer'

    szg_feed.elastic_search_items_provider_attributes_normalizer:
        class: "%szg_feed.elastic_search_items_provider_attributes_normalizer_class%"
        public: false
        arguments:
          - '@kunstmaan_extra.content_category'
          - '@szg_feed.feed_chain'
          - '@szg_feed.services_resolver.node_id_resolver_service'

    szg_feed.services_resolver.node_id_resolver_service:
        class: SZG\KunstmaanFeedBundle\Services\Resolver\NodeIdResolverService
        arguments: ['@kunstmaan_extra.public_node_versions']

    szg_feed.twig.feed_extension:
        class: SZG\KunstmaanFeedBundle\Services\Twig\FeedExtension
        arguments: ["@szg_feed.elastic_search_items_provider"]
        public: false
        tags:
            - { name: twig.extension }
